from __future__ import annotations
import os
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak
NAVY=colors.HexColor('#1f4e79'); ORANGE=colors.HexColor('#c55a11'); RED=colors.HexColor('#c00000'); LIGHT=colors.HexColor('#f2f2f2')
def chart(metric,path):
    fig,ax=plt.subplots(figsize=(8,3),dpi=150); h=metric['historical']; f=metric['forecast']; x=[p['t'] for p in h]; y=[p['v'] for p in h]; xf=[p['t'] for p in f]; yf=[p['v'] for p in f]; lo=[p['v'] for p in metric['lower']]; hi=[p['v'] for p in metric['upper']]
    ax.plot(x,y,label='Historical'); ax.plot(xf,yf,'--',label='Forecast'); ax.fill_between(xf,lo,hi,alpha=.15,label='95% confidence band')
    if metric['cap']: ax.axhline(metric['cap']*.8,linestyle=':',alpha=.6,label='80% threshold')
    ax.set_title(f"{metric['label']} — Trend & Forecast",fontsize=10,fontweight='bold'); ax.grid(alpha=.2); ax.legend(fontsize=7,loc='upper left',frameon=False); ax.xaxis.set_major_locator(mdates.AutoDateLocator()); ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d')); fig.autofmt_xdate(); fig.tight_layout(); fig.savefig(path,bbox_inches='tight'); plt.close(fig)
def styles():
    s=getSampleStyleSheet(); s.add(ParagraphStyle('TitleX',parent=s['Title'],fontSize=26,textColor=NAVY,spaceAfter=6)); s.add(ParagraphStyle('H1X',parent=s['Heading1'],textColor=NAVY,spaceBefore=18,spaceAfter=8)); s.add(ParagraphStyle('H2X',parent=s['Heading2'],textColor=ORANGE,spaceBefore=12,spaceAfter=6)); s.add(ParagraphStyle('BodyX',parent=s['BodyText'],fontSize=10,leading=14)); s.add(ParagraphStyle('Cell',parent=s['BodyText'],fontSize=8.5,leading=10)); s.add(ParagraphStyle('CellW',parent=s['BodyText'],fontSize=8.5,leading=10,textColor=colors.white)); return s
def fmt(v,unit):
    if v is None:return 'N/A'
    if unit=='%':return f'{v:,.1f}%'
    if unit=='ms':return f'{v:,.2f} ms'
    if unit=='Count':return f'{v:,.0f}'
    if unit=='BytePerSecond': return f'{v/1e6:,.2f} MB/s' if v>=1e6 else f'{v:,.0f} B/s'
    return f'{v:,.2f}'
def build_pdf_report(path,company,title,a):
    s=styles(); doc=SimpleDocTemplate(path,pagesize=LETTER,leftMargin=.75*inch,rightMargin=.75*inch,topMargin=.8*inch,bottomMargin=.7*inch,title=title,author=company); story=[]; z=a['management_zone']; start=a['summary']['from']; end=a['summary']['to']
    story += [Spacer(1,1.5*inch),Paragraph(title,s['TitleX']),Paragraph(f'Management Zone: <b>{z}</b>',s['BodyX']),Spacer(1,6),Paragraph(f'Assessment Period: {start} – {end} | Forecast Horizon: 90 days',s['BodyX']),Spacer(1,2.1*inch),Paragraph(company,s['H2X']),Paragraph('Generated by Capacity Planner — Mock Excel Data',s['BodyX']),PageBreak()]
    inc=sum(v['direction']=='increasing' for v in a['trends'].values()); dec=sum(v['direction']=='decreasing' for v in a['trends'].values()); flat=6-inc-dec
    story += [Paragraph('Executive Summary',s['H1X']),Paragraph(f"This report assesses infrastructure capacity and application performance for the <b>{z}</b> management zone over the selected historical period and projects expected behavior over the next 90 days based on observed trends. Of 6 tracked metrics, <b>{inc}</b> show an increasing trend, <b>{dec}</b> are decreasing, and <b>{flat}</b> remain stable. During the assessment window, the mock dataset contains <b>{a['summary']['problems']}</b> problem records; the correlation and problem sections are included to mirror the original report workflow.",s['BodyX']),Spacer(1,10)]
    rows=[[Paragraph(x,s['CellW']) for x in ['Metric','Category','Direction','% Change','Current Value']]]
    for k,m in a['metrics'].items():
        t=a['trends'][k]; arrow='▲' if t['direction']=='increasing' else '▼' if t['direction']=='decreasing' else '■'; rows.append([Paragraph(m['label'],s['Cell']),Paragraph(m['category'],s['Cell']),Paragraph(f'{arrow} {t["direction"].title()}',s['Cell']),Paragraph(f"{t['change']:.1f}%",s['Cell']),Paragraph(fmt(t['end'],m['unit']),s['Cell'])])
    tbl=Table(rows,colWidths=[1.8*inch,1.1*inch,1.1*inch,.8*inch,1.5*inch]); tbl.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),NAVY),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,LIGHT]),('GRID',(0,0),(-1,-1),.4,colors.lightgrey),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)])); story += [tbl,PageBreak()]
    for idx,k in enumerate(['host_cpu_usage','host_mem_usage','host_disk_used_pct','network_traffic']):
        if idx%2==0: story.append(Paragraph('Infrastructure Metrics',s['H1X']))
        m=a['metrics'][k]; t=a['trends'][k]; tmp=f'/tmp/{os.path.basename(path)}_{k}.png'; chart(m,tmp); story += [Paragraph(m['label'],s['H2X']),Image(tmp,width=6.55*inch,height=2.35*inch),Paragraph(f"Over the assessment period, this metric averaged {fmt(t['mean'],m['unit'])} and moved from {fmt(t['start'],m['unit'])} to {fmt(t['end'],m['unit'])} ({t['change']:.1f}% change), a <b>{t['direction']}</b> trend (slope ≈ {t['slope']:.3f} {m['unit']}/day).",s['BodyX'])]
        if idx in (1,3): story.append(PageBreak())
    story += [Paragraph('Host Resource Utilization',s['H1X']),Paragraph('Averages are over the assessment window; forecast columns project each host trend roughly three months ahead so hosts trending toward capacity are visible even when the overall average remains comfortable.',s['BodyX']),Spacer(1,8)]
    hr=[[Paragraph(x,s['CellW']) for x in ['Host','CPU Avg %','CPU 3-Mo Fcst','Mem Avg %','Mem 3-Mo Fcst','Disk Avg %','Disk 3-Mo Fcst','Status']]]
    for r in a['host_table']: hr.append([Paragraph(r['host'],s['Cell']),Paragraph(f"{r['cpu_pct_avg']:.1f}",s['Cell']),Paragraph(f"{r['cpu_pct_forecast']:.1f}",s['Cell']),Paragraph(f"{r['memory_pct_avg']:.1f}",s['Cell']),Paragraph(f"{r['memory_pct_forecast']:.1f}",s['Cell']),Paragraph(f"{r['disk_pct_avg']:.1f}",s['Cell']),Paragraph(f"{r['disk_pct_forecast']:.1f}",s['Cell']),Paragraph(r['status'],s['Cell'])])
    ht=Table(hr,colWidths=[2.15*inch,.55*inch,.7*inch,.55*inch,.75*inch,.55*inch,.75*inch,.65*inch]); ht.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),NAVY),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,LIGHT]),('GRID',(0,0),(-1,-1),.35,colors.lightgrey),('FONTSIZE',(0,0),(-1,-1),7)])); story += [ht,PageBreak()]
    story += [Paragraph('Performance Metrics',s['H1X'])]
    for k in ['service_request_count','service_response_time']:
        m=a['metrics'][k]; t=a['trends'][k]; tmp=f'/tmp/{os.path.basename(path)}_{k}.png'; chart(m,tmp); story += [Paragraph(m['label'],s['H2X']),Image(tmp,width=6.55*inch,height=2.45*inch),Paragraph(f"Over the assessment period, this metric averaged {fmt(t['mean'],m['unit'])} and moved from {fmt(t['start'],m['unit'])} to {fmt(t['end'],m['unit'])} ({t['change']:.1f}% change), a <b>{t['direction']}</b> trend.",s['BodyX'])]
    story.append(PageBreak())
    story += [Paragraph('Problem Correlation Analysis',s['H1X']),Paragraph('Top 10 Longest-Duration Problems',s['H2X'])]
    p=a['problems'].sort_values('duration_min',ascending=False).head(10); pr=[[Paragraph(x,s['CellW']) for x in ['Title','Severity','Status','Start','Duration (min)']]]
    for _,r in p.iterrows(): pr.append([Paragraph(str(r.title),s['Cell']),Paragraph(str(r.severity),s['Cell']),Paragraph(str(r.status),s['Cell']),Paragraph(pd.Timestamp(r.startTime).strftime('%d %b %Y %H:%M'),s['Cell']),Paragraph(f"{int(r.duration_min):,}",s['Cell'])])
    pt=Table(pr,colWidths=[2.35*inch,1.25*inch,.75*inch,1.2*inch,.9*inch]); pt.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),RED),('TEXTCOLOR',(0,0),(-1,0),colors.white),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,LIGHT]),('GRID',(0,0),(-1,-1),.35,colors.lightgrey)])); story += [pt,PageBreak()]
    story += [Paragraph('Capacity Planning Recommendations',s['H1X']),Paragraph('Analysis Engine summary',s['BodyX']),Paragraph(f"The analysis combines utilization trends, forward-looking forecasts and host-level projections. {sum(r['status']=='At Risk' for r in a['host_table'])} host(s) are individually flagged At Risk and {sum(r['status']=='Watch' for r in a['host_table'])} are on Watch.",s['BodyX']),Spacer(1,10),Paragraph('What-If Capacity Simulation',s['H2X']),Paragraph(f"This scenario models the selected {a['growth']:+.0f}% change in service request volume. Resource projections are scaled directionally for planning comparison.",s['BodyX'])]
    rr=[[Paragraph(x,s['CellW']) for x in ['Growth','CPU Peak','Memory Peak','Disk Peak']]]
    for x in a['scenarios']: rr.append([Paragraph(f"{x['growth']:+.0f}%",s['Cell']),Paragraph(f"{x['cpu']:.1f}%",s['Cell']),Paragraph(f"{x['memory']:.1f}%",s['Cell']),Paragraph(f"{x['disk']:.1f}%",s['Cell'])])
    rt=Table(rr,colWidths=[1.2*inch,1.2*inch,1.3*inch,1.2*inch]); rt.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),NAVY),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,LIGHT]),('GRID',(0,0),(-1,-1),.4,colors.lightgrey)])); story += [rt,Spacer(1,14),Paragraph('Host-Level Problem Correlation',s['H2X'])]
    for r in a['recommendations'][:6]: story.append(Paragraph(f"• {r['host']} — <b>{r['risk']}</b>: {r['action']}",s['BodyX']))
    doc.build(story)
