from __future__ import annotations

import os

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

NAVY = colors.HexColor("#1f4e79")
ORANGE = colors.HexColor("#c55a11")
RED = colors.HexColor("#c00000")
LIGHT = colors.HexColor("#f2f2f2")


def chart(metric, path):
    fig, ax = plt.subplots(figsize=(8, 3), dpi=150)
    h = metric["historical"]
    f = metric["forecast"]
    x = [p["t"] for p in h]
    y = [p["v"] for p in h]
    xf = [p["t"] for p in f]
    yf = [p["v"] for p in f]
    lo = [p["v"] for p in metric["lower"]]
    hi = [p["v"] for p in metric["upper"]]
    ax.plot(x, y, label="Historical")
    ax.plot(xf, yf, "--", label="Forecast")
    ax.fill_between(xf, lo, hi, alpha=0.15, label="95% confidence band")
    if metric["cap"]:
        ax.axhline(metric["cap"] * 0.8, linestyle=":", alpha=0.6, label="80% threshold")
    ax.set_title(f"{metric['label']} — Trend & Forecast", fontsize=10, fontweight="bold")
    ax.grid(alpha=0.2)
    ax.legend(fontsize=7, loc="upper left", frameon=False)
    ax.xaxis.set_major_locator(mdates.AutoDateLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
    fig.autofmt_xdate()
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)


def styles():
    s = getSampleStyleSheet()
    s.add(ParagraphStyle("TitleX", parent=s["Title"], fontSize=26, textColor=NAVY, spaceAfter=6))
    s.add(ParagraphStyle("H1X", parent=s["Heading1"], textColor=NAVY, spaceBefore=18, spaceAfter=8))
    s.add(ParagraphStyle("H2X", parent=s["Heading2"], textColor=ORANGE, spaceBefore=12, spaceAfter=6))
    s.add(ParagraphStyle("BodyX", parent=s["BodyText"], fontSize=10, leading=14))
    s.add(ParagraphStyle("Cell", parent=s["BodyText"], fontSize=8.5, leading=10))
    s.add(ParagraphStyle("CellW", parent=s["BodyText"], fontSize=8.5, leading=10, textColor=colors.white))
    return s


def fmt(v, unit):
    if v is None:
        return "N/A"
    if unit == "%":
        return f"{v:,.1f}%"
    if unit == "ms":
        return f"{v:,.2f} ms"
    if unit == "Count":
        return f"{v:,.0f}"
    if unit == "BytePerSecond":
        return f"{v / 1e6:,.2f} MB/s" if v >= 1e6 else f"{v:,.0f} B/s"
    return f"{v:,.2f}"


def _table(data, widths, header_color=NAVY):
    table = Table(data, colWidths=widths, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), header_color),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return table


def build_pdf_report(path, company, title, a):
    s = styles()
    doc = SimpleDocTemplate(path, pagesize=LETTER, leftMargin=.75 * inch, rightMargin=.75 * inch, topMargin=.8 * inch, bottomMargin=.7 * inch, title=title, author=company)
    story = []
    z = a["management_zone"]
    start = a["summary"]["from"]
    end = a["summary"]["to"]
    horizon = a["summary"].get("forecast_days", 90)
    source = a["summary"].get("data_source", "mock").title()

    story += [Spacer(1, 1.5 * inch), Paragraph(title, s["TitleX"]), Paragraph(f"Management Zone: <b>{z}</b>", s["BodyX"]), Spacer(1, 6), Paragraph(f"Assessment Period: {start} – {end} | Forecast Horizon: {horizon} days", s["BodyX"]), Spacer(1, 2.1 * inch), Paragraph(company, s["H2X"]), Paragraph(f"Generated by Capacity Planner — {source} Data", s["BodyX"]), PageBreak()]

    inc = sum(v["direction"] == "increasing" for v in a["trends"].values())
    dec = sum(v["direction"] == "decreasing" for v in a["trends"].values())
    flat = 6 - inc - dec
    story += [Paragraph("Executive Summary", s["H1X"]), Paragraph(f"This report assesses infrastructure capacity and application performance for the <b>{z}</b> management zone over the selected historical period and projects expected behavior over the next <b>{horizon} days</b>. Of 6 tracked metrics, <b>{inc}</b> show an increasing trend, <b>{dec}</b> are decreasing, and <b>{flat}</b> remain stable. The dataset contains <b>{a['summary']['applications']}</b> applications and <b>{a['summary']['problems']}</b> problem records.", s["BodyX"]), Spacer(1, 10)]

    rows = [[Paragraph(x, s["CellW"]) for x in ["Metric", "Category", "Direction", "% Change", "Current Value"]]]
    for k, m in a["metrics"].items():
        t = a["trends"][k]
        arrow = "▲" if t["direction"] == "increasing" else "▼" if t["direction"] == "decreasing" else "■"
        rows.append([Paragraph(m["label"], s["Cell"]), Paragraph(m["category"], s["Cell"]), Paragraph(f'{arrow} {t["direction"].title()}', s["Cell"]), Paragraph(f'{t["change"]:.1f}%', s["Cell"]), Paragraph(fmt(t["end"], m["unit"]), s["Cell"])])
    story += [_table(rows, [1.8 * inch, 1.1 * inch, 1.1 * inch, .8 * inch, 1.5 * inch]), PageBreak()]

    for idx, k in enumerate(["host_cpu_usage", "host_mem_usage", "host_disk_used_pct", "network_traffic"]):
        if idx % 2 == 0:
            story.append(Paragraph("Infrastructure Metrics", s["H1X"]))
        m = a["metrics"][k]
        t = a["trends"][k]
        tmp = f"/tmp/{os.path.basename(path)}_{k}.png"
        if not m["historical"]:
            story += [Paragraph(m["label"], s["H2X"]), Paragraph("No data was supplied for this metric by the selected data source.", s["BodyX"])]
        else:
            chart(m, tmp)
            story += [Paragraph(m["label"], s["H2X"]), Image(tmp, width=6.55 * inch, height=2.35 * inch), Paragraph(f"Over the assessment period, this metric averaged {fmt(t['mean'], m['unit'])} and moved from {fmt(t['start'], m['unit'])} to {fmt(t['end'], m['unit'])} ({t['change']:.1f}% change), a <b>{t['direction']}</b> trend.", s["BodyX"])]
        if idx in (1, 3):
            story.append(PageBreak())

    story += [Paragraph("Application-wise Capacity View", s["H1X"]), Paragraph("The capacity view is intentionally application-wise. Server/host identifiers are not shown to the user; each row represents an application/service workload and its forward request and response-time outlook.", s["BodyX"]), Spacer(1, 8)]
    ar = [[Paragraph(x, s["CellW"]) for x in ["Application", "Avg Requests", "Avg Response", "Forecast Requests", "Forecast Response", "Status"]]]
    for r in a["application_table"]:
        ar.append([Paragraph(str(r["application"]), s["Cell"]), Paragraph(f'{r["requests_avg"]:,.0f}', s["Cell"]), Paragraph(f'{r["response_avg"]:,.1f} ms', s["Cell"]), Paragraph(f'{r["request_forecast"]:,.0f}', s["Cell"]), Paragraph(f'{r["response_forecast"]:,.1f} ms', s["Cell"]), Paragraph(str(r["status"]), s["Cell"])])
    story += [_table(ar, [1.55 * inch, .9 * inch, 1.0 * inch, 1.05 * inch, 1.15 * inch, .75 * inch]), PageBreak()]

    story += [Paragraph("Performance Metrics", s["H1X"])]
    for k in ["service_request_count", "service_response_time"]:
        m = a["metrics"][k]
        t = a["trends"][k]
        tmp = f"/tmp/{os.path.basename(path)}_{k}.png"
        if m["historical"]:
            chart(m, tmp)
            story += [Paragraph(m["label"], s["H2X"]), Image(tmp, width=6.55 * inch, height=2.45 * inch), Paragraph(f"Over the assessment period, this metric averaged {fmt(t['mean'], m['unit'])} and moved from {fmt(t['start'], m['unit'])} to {fmt(t['end'], m['unit'])} ({t['change']:.1f}% change), a <b>{t['direction']}</b> trend.", s["BodyX"])]
        else:
            story += [Paragraph(m["label"], s["H2X"]), Paragraph("No data was supplied for this metric by the selected data source.", s["BodyX"])]
    story.append(PageBreak())

    story += [Paragraph("Problem Correlation Analysis", s["H1X"]), Paragraph("Top 10 Longest-Duration Problems", s["H2X"])]
    problems = a["problems"]
    if problems is None or problems.empty:
        story.append(Paragraph("No problem records were supplied by the selected data source.", s["BodyX"]))
    else:
        p = problems.sort_values("duration_min", ascending=False).head(10)
        pr = [[Paragraph(x, s["CellW"]) for x in ["Application", "Title", "Severity", "Status", "Duration (min)"]]]
        for _, r in p.iterrows():
            pr.append([Paragraph(str(r.get("application", "")), s["Cell"]), Paragraph(str(r.title), s["Cell"]), Paragraph(str(r.severity), s["Cell"]), Paragraph(str(r.status), s["Cell"]), Paragraph(f"{int(r.duration_min):,}", s["Cell"])])
        story.append(_table(pr, [1.25 * inch, 2.15 * inch, 1.1 * inch, .75 * inch, .9 * inch], RED))
    story.append(PageBreak())

    story += [Paragraph("Capacity Planning Recommendations", s["H1X"]), Paragraph("Analysis Engine summary", s["BodyX"]), Paragraph(f"The analysis combines utilization trends, forward-looking forecasts and application-level performance projections. {sum(r['status'] == 'At Risk' for r in a['application_table'])} application(s) are individually flagged At Risk and {sum(r['status'] == 'Watch' for r in a['application_table'])} are on Watch.", s["BodyX"]), Spacer(1, 10), Paragraph("What-If Capacity Simulation", s["H2X"]), Paragraph(f"This scenario models the selected {a['growth']:+.0f}% change in service request volume. Resource projections are scaled directionally for planning comparison.", s["BodyX"])]
    rr = [[Paragraph(x, s["CellW"]) for x in ["Growth", "CPU Peak", "Memory Peak", "Disk Peak"]]]
    for x in a["scenarios"]:
        rr.append([Paragraph(f"{x['growth']:+.0f}%", s["Cell"]), Paragraph(f"{x['cpu']:.1f}%", s["Cell"]), Paragraph(f"{x['memory']:.1f}%", s["Cell"]), Paragraph(f"{x['disk']:.1f}%", s["Cell"])])
    story += [_table(rr, [1.2 * inch, 1.2 * inch, 1.3 * inch, 1.2 * inch]), Spacer(1, 14), Paragraph("Application-Level Problem Correlation", s["H2X"])]
    for r in a["recommendations"][:6]:
        story.append(Paragraph(f"• {r['application']} — <b>{r['risk']}</b>: {r['action']}", s["BodyX"]))

    doc.build(story)
