from __future__ import annotations
import os
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle,getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Image,PageBreak,Paragraph,SimpleDocTemplate,Spacer,Table,TableStyle
NAVY=colors.HexColor('#1f4e79');ORANGE=colors.HexColor('#c55a11');LIGHT=colors.HexColor('#f2f2f2')
def fmt(v,u):
 if v is None:return 'N/A'
 v=float(v)
 if u=='%':return f'{v:,.1f}%'
 if u=='Count':return f'{v:,.0f}'
 if u=='Rate':return f'{v:,.1f}'
 if u=='BytePerSecond':return f'{v/1e6:,.1f} MB/s' if v>=1e6 else f'{v:,.0f} B/s'
 if u=='ms':return f'{v:,.1f} ms'
 return f'{v:,.1f}'
def styles():
 s=getSampleStyleSheet();s.add(ParagraphStyle('TitleX',parent=s['Title'],fontSize=26,textColor=NAVY));s.add(ParagraphStyle('H1X',parent=s['Heading1'],textColor=NAVY,spaceBefore=18,spaceAfter=8));s.add(ParagraphStyle('H2X',parent=s['Heading2'],textColor=ORANGE,spaceBefore=12,spaceAfter=6));s.add(ParagraphStyle('BodyX',parent=s['BodyText'],fontSize=10,leading=14));s.add(ParagraphStyle('Cell',parent=s['BodyText'],fontSize=8.2,leading=10));s.add(ParagraphStyle('CellW',parent=s['BodyText'],fontSize=8.2,leading=10,textColor=colors.white));return s
def table(rows,widths):
 t=Table(rows,colWidths=widths,repeatRows=1);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),NAVY),('TEXTCOLOR',(0,0),(-1,0),colors.white),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,LIGHT]),('GRID',(0,0),(-1,-1),.35,colors.lightgrey),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]));return t
def chart(m,path):
 fig,ax=plt.subplots(figsize=(8,3),dpi=150);h,f=m.get('historical',[]),m.get('forecast',[])
 if h:ax.plot([p['t'] for p in h],[p['v'] for p in h],label='Historical')
 if f:ax.plot([p['t'] for p in f],[p['v'] for p in f],'--',label='Forecast')
 if m.get('lower') and m.get('upper'):ax.fill_between([p['t'] for p in f],[p['v'] for p in m['lower']],[p['v'] for p in m['upper']],alpha=.15,label='95% confidence band')
 if m.get('cap'):ax.axhline(m['cap']*.8,linestyle=':',alpha=.6,label='80% threshold')
 ax.set_title(f"{m['label']} — Trend & Forecast",fontsize=10,fontweight='bold');ax.grid(alpha=.2);ax.legend(fontsize=7,loc='upper left',frameon=False);ax.xaxis.set_major_locator(mdates.AutoDateLocator());ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'));fig.autofmt_xdate();fig.tight_layout();fig.savefig(path,bbox_inches='tight');plt.close(fig)
def build_pdf_report(path,company,title,a):
 s=styles();doc=SimpleDocTemplate(path,pagesize=LETTER,leftMargin=.7*inch,rightMargin=.7*inch,topMargin=.75*inch,bottomMargin=.65*inch,title=title,author=company);story=[];sel=a['application'];summary=a['summary'];conf=summary.get('model_confidence','Not assessed');growth=float(a.get('growth',0));sim=a.get('simulation',{});base_cpu=a['metrics']['host_cpu_usage']['forecast'][-1]['v'] if a['metrics']['host_cpu_usage']['forecast'] else None;base_mem=a['metrics']['host_mem_usage']['forecast'][-1]['v'] if a['metrics']['host_mem_usage']['forecast'] else None;base_disk=a['metrics']['host_disk_used_pct']['forecast'][-1]['v'] if a['metrics']['host_disk_used_pct']['forecast'] else None;base_jvm=a['metrics']['service_response_time']['forecast'][-1]['v'] if a['metrics']['service_response_time']['forecast'] else None
 selected_cpu=sim.get('host_cpu_usage',{}).get('simulated',base_cpu);selected_mem=sim.get('host_mem_usage',{}).get('simulated',base_mem);selected_disk=sim.get('host_disk_used_pct',{}).get('simulated',base_disk);selected_jvm=sim.get('service_response_time',{}).get('simulated',base_jvm)
 if summary.get('data_source')=='zip' and base_jvm is not None:selected_jvm=max(0,base_jvm*(1+0.20*growth/100))
 selected_cpu=None if selected_cpu is None else min(100,float(selected_cpu));selected_mem=None if selected_mem is None else min(100,float(selected_mem));selected_disk=None if selected_disk is None else min(100,float(selected_disk));selected_headroom={'host_cpu_usage':None if selected_cpu is None else max(0,100-selected_cpu),'host_mem_usage':None if selected_mem is None else max(0,100-selected_mem),'host_disk_used_pct':None if selected_disk is None else max(0,100-selected_disk)}
 story += [Spacer(1,1.2*inch),Paragraph(title,s['TitleX']),Paragraph(f'Selected Application: <b>{sel}</b>',s['BodyX']),Paragraph(f"Management Zone / Dataset: <b>{a['management_zone']}</b>",s['BodyX']),Spacer(1,6),Paragraph(f"Assessment Period: {summary['from']} – {summary['to']} | Forecast Horizon: {summary['forecast_days']} days",s['BodyX']),Spacer(1,1.6*inch),Paragraph(company,s['H2X']),Paragraph(f"Generated by Capacity Planner — {summary.get('data_source_label','Uploaded Data')}",s['BodyX']),PageBreak()]
 story += [Paragraph('Executive Summary',s['H1X']),Paragraph(f"The selected <b>{sel}</b> is evaluated in six steps: historical baseline, future forecast, workload scenario, capacity impact, resource headroom and planning recommendation. Forecast confidence is <b>{conf}</b>.",s['BodyX']),Spacer(1,8)]
 semantic=(f"Workload driver: <b>{summary.get('workload_label','HTTP Request Volume')}</b>. Performance metric: <b>{summary.get('performance_label','Response Time')}</b>." if summary.get('has_http_requests') else f"Workload driver: <b>{summary.get('workload_label','Workload proxy')}</b>. Performance/resource metric: <b>{summary.get('performance_label','JVM Threads')}</b>. The uploaded dataset does not contain HTTP request volume or response-time measurements.")
 story += [Paragraph(semantic,s['BodyX']),Spacer(1,8)]
 rows=[[Paragraph(x,s['CellW']) for x in ['Metric','Category','Recent change','Current','Forecast','Model']]]
 for k,m in a['metrics'].items():
  t=a['trends'][k];chg='N/A' if t['change'] is None else f"{t['change']:.1f}%";model=m.get('model',{}).get('model','N/A');rows.append([Paragraph(m['label'],s['Cell']),Paragraph(m['category'],s['Cell']),Paragraph(chg,s['Cell']),Paragraph(fmt(t['end'],m['unit']),s['Cell']),Paragraph(fmt(m['forecast'][-1]['v'] if m['forecast'] else None,m['unit']),s['Cell']),Paragraph(model,s['Cell'])])
 story += [table(rows,[1.55*inch,1*inch,.85*inch,1*inch,1*inch,1.1*inch]),PageBreak(),Paragraph('Capacity Headroom',s['H1X'])]
 rows=[[Paragraph(x,s['CellW']) for x in ['Resource','Scenario utilization','Available headroom']]]
 for k,label,val in [('host_cpu_usage','CPU',selected_cpu),('host_mem_usage','Memory',selected_mem),('host_disk_used_pct','Disk',selected_disk)]:rows.append([Paragraph(label,s['Cell']),Paragraph(fmt(val,'%'),s['Cell']),Paragraph(fmt(selected_headroom[k],'%'),s['Cell'])])
 story += [table(rows,[2*inch,2*inch,2*inch]),Spacer(1,10),Paragraph(f"Headroom is calculated from the selected <b>{growth:+.0f}%</b> workload scenario: 100% minus scenario utilization for bounded utilization metrics. It is a planning indicator, not a vendor-specific capacity limit.",s['BodyX']),PageBreak()]
 for idx,k in enumerate(['host_cpu_usage','host_mem_usage','host_disk_used_pct','network_traffic']):
  m=a['metrics'][k];t=a['trends'][k];tmp=f'/tmp/{os.path.basename(path)}_{k}.png';story.append(Paragraph(m['label'],s['H2X']))
  if m['historical']:
   chart(m,tmp);chg='N/A' if t['change'] is None else f'{t["change"]:.1f}%';story += [Image(tmp,width=6.5*inch,height=2.3*inch),Paragraph(f"Current {fmt(t['end'],m['unit'])}; forecast {fmt(m['forecast'][-1]['v'] if m['forecast'] else None,m['unit'])}; recent-window change {chg}; model {m.get('model',{}).get('model','N/A')} with {m.get('model',{}).get('confidence','N/A')} confidence.",s['BodyX'])]
  else:story.append(Paragraph('No data was supplied for this metric by the selected data source/application.',s['BodyX']))
  if idx in (1,3):story.append(PageBreak())
 story += [Paragraph('Application-wise Capacity View',s['H1X']),Paragraph(summary.get('application_group_note','Application names are taken from the supplied dataset.'),s['BodyX']),Spacer(1,8)]
 rows=[[Paragraph(x,s['CellW']) for x in ['Application','Recent workload','Recent performance','Scenario workload','Scenario performance','Status']]]
 scenario_work=None;base_work=float(a['metrics']['service_request_count']['forecast'][-1]['v']) if a['metrics']['service_request_count']['forecast'] else None
 if base_work is not None:scenario_work=base_work*(1+growth/100)
 for r in a['application_table']:rows.append([Paragraph(str(r['application']),s['Cell']),Paragraph(fmt(r['requests_avg'],a['metrics']['service_request_count']['unit']),s['Cell']),Paragraph(fmt(r['response_avg'],a['metrics']['service_response_time']['unit']),s['Cell']),Paragraph(fmt(scenario_work,a['metrics']['service_request_count']['unit']),s['Cell']),Paragraph(fmt(selected_jvm,a['metrics']['service_response_time']['unit']),s['Cell']),Paragraph(str(r['status']),s['Cell'])])
 story += [table(rows,[1.55*inch,1.05*inch,1.15*inch,1.1*inch,1.15*inch,.75*inch]),PageBreak(),Paragraph('Workload Scenario & Capacity Impact',s['H1X']),Paragraph(f"Selected scenario: <b>{growth:+.0f}%</b>. {summary.get('simulation_note','')}",s['BodyX']),Spacer(1,8)]
 selected_work=scenario_work
 rows=[[Paragraph(x,s['CellW']) for x in ['Scenario','Workload','CPU','Memory','Disk','Performance']]]
 rows.append([Paragraph(f"Selected {growth:+.0f}%",s['Cell']),Paragraph(fmt(selected_work,'Rate'),s['Cell']),Paragraph(fmt(selected_cpu,'%'),s['Cell']),Paragraph(fmt(selected_mem,'%'),s['Cell']),Paragraph(fmt(selected_disk,'%'),s['Cell']),Paragraph(fmt(selected_jvm,a['metrics']['service_response_time']['unit']),s['Cell'])])
 for x in a['scenarios']:
  ref_perf=x.get('performance')
  if summary.get('data_source')=='zip' and base_jvm is not None:ref_perf=max(0,base_jvm*(1+0.20*float(x['growth'])/100))
  rows.append([Paragraph(f"Reference {x['growth']:+.0f}%",s['Cell']),Paragraph(fmt(x.get('workload'),'Rate'),s['Cell']),Paragraph(fmt(x.get('cpu'),'%'),s['Cell']),Paragraph(fmt(x.get('memory'),'%'),s['Cell']),Paragraph(fmt(x.get('disk'),'%'),s['Cell']),Paragraph(fmt(ref_perf,a['metrics']['service_response_time']['unit']),s['Cell'])])
 method_note='For the uploaded ZIP, CPU, memory and JVM impact uses a conservative workload-sensitivity model when the historical workload/resource correlation is too weak for regression. This keeps the scenario responsive to the selected workload while avoiding an unsupported claim of direct measured causality.' if summary.get('data_source')=='zip' else 'Workload simulation uses regression where the historical workload/resource relationship is sufficiently supported; otherwise the baseline forecast is retained.'
 story += [table(rows,[1.05*inch,1.05*inch,.9*inch,.95*inch,.85*inch,1.1*inch]),Spacer(1,8),Paragraph(f"<b>Selected scenario result:</b> workload changes from {fmt(base_work,'Rate')} baseline forecast to {fmt(selected_work,'Rate')}. CPU, memory and performance forecasts respond according to the selected simulation method.",s['BodyX']),Spacer(1,14),Paragraph('Forecast Method',s['H2X']),Paragraph('The engine aggregates historical observations to daily values, interpolates missing points, limits extreme outliers, evaluates a recent-median model, Holt-Winters and trend regression on a holdout period, and selects the lowest-error model. '+method_note,s['BodyX']),Spacer(1,8),Paragraph('Planning Recommendation',s['H2X']),Paragraph(a['recommendations'][0]['action'],s['BodyX'])]
 doc.build(story)
